Remove redis references
ONSdigital/ssdc-rm-docker-dev pull request #103
Opened 2024-05-29 16:00 UTC by KieranWardle

# Motivation and Context
We no longer use redis for RH-UI

# What has changed
removed redis from docker-compose files

2024-05-30 10:32 UTC, ryangrundy7 requested changes
I think for this to work you need to do the work we mentioned on this ticket https://jira.ons.gov.uk/browse/SDCSRM-480

2024-05-30 10:32 UTC, ryangrundy7 commented on rm-services.yml
So by doing this you break the old RH-UI. The RH-UI is currently used to against the acceptance tests so it will make the local tests fail. I think you may as well remove the old rh-ui and update the acceptance tests as part of this ticket. If removing Redis breaks the old RH-UI there's no point in it being there

2024-06-12 09:19 UTC, ryangrundy7 approved these changes

2024-06-13 08:44 UTC, dbanks91 approved these changes
Looks good to me 👍

2024-06-14 08:12 UTC, merged