Add rh docker dev
ONSdigital/ssdc-rm-docker-dev pull request #51
Opened 2022-04-13 12:48 UTC by hbrace

# Motivation and Context

We want to bring the RH services into docker dev.
# What has changed

rh-services.yml and rh-dev.yml created to hold the RH docker services and dependant containers.
Makefile has been updated so that there are targes for `up`, `down`, `pul`l and `logs` for RH and RM individually, as well as for both at the same time.
# How to test?

Test the make targets and ensure everything comes up and down as required.
Note, if bring up both RM and RH services, and then stop one or the other, the pubsub emulator will not stay up so you will need to run the `*-up` target for the services you wanted to stay up.

Run the ATs (will not work with the RH stuff up)
Run the RH cucumber tests (with changes on the linked branch of the same name)
# Links

https://trello.com/c/zPH8WtWD/3401-bring-rh-into-our-docker-compose-setup8
# Screenshots (if appropriate):

2022-04-14 07:23 UTC, AdamHawtin requested changes
All seems to be working, but I've added some suggestions on keeping the old make targets and handling the common pubsub dependency.

2022-04-14 07:23 UTC, AdamHawtin commented on Makefile
> -up:
Can we preserve `make up`?

2022-04-14 07:23 UTC, AdamHawtin commented on Makefile
> -down:
Can we preserve `make down` as a command to stop everything? There's no harm passing docker compose down extra docker compose files, even if they haven't been started.

2022-04-14 07:23 UTC, AdamHawtin commented on Makefile
> +	@echo "IF RH IS RUNNING, THIS WILL STOP PUBUSB EMULATOR FOR THOSE SERVICES TOO"
Can we solve this by keeping the common services in a separate YAML and not stopping them on these specific `down` commands?

2022-04-14 07:23 UTC, AdamHawtin commented on Makefile
> -pull:
Can we keep `make pull` as a command to pull everything?

2022-04-14 07:23 UTC, AdamHawtin commented on Makefile
> +rm-logs:
I don't think we need separate, specific `logs` targets, we could just have one which looks across all our docker compose files

2022-04-14 07:23 UTC, AdamHawtin commented on rh-dev.yml
> +      - "8538:8538"
I don't think we should duplicate the pubsub-emulator container config, better to split out the common dependencies on their own.

2022-04-14 08:07 UTC, AdamHawtin commented on Makefile
> -logs:
Could we keep a `logs` target to see everything?

2022-04-14 12:08 UTC, AdamHawtin approved these changes
👍 LGTM, passes RH AT's and RM's ATs (when RH isn't running).

2022-04-19 09:23 UTC, LukeLoze1 approved these changes

2022-04-19 10:50 UTC, merged